redhat-developer/rpm-packaging-guide

source/packaging-software.adoc

There is no %setup section, but %setup macro used in %prep section.

Change %setup section to %prep section.

---

source/advanced-topics.adoc

Several issues I found in a Mock chapter.

Fixes for Mock chapter

---

community/index.adoc
rhel/master.adoc

add H3 to TOC

---

community/index.adoc
rhel/master.adoc
source/hello-world.adoc

the most simple spec file you can create

add hello world example

---

source/advanced-topics.adoc

This is heavily inspired by:
http://www.abclinuxu.cz/clanky/navody/rukovet-balice-rpm-vi-makro-setup#rpm6-mocne-makro-setup

Add %setup macro description.

---

source/packaging-software.adoc

Hi Guys,
this is a simple fix for two typos.
Cheers,
Radek

Fix - directory to directive

---

source/hello-world.adoc

Edited chapter "Your First RPM Package"

---

source/advanced-topics.adoc

Edited chapter Defining Your Own Macros

---

source/advanced-topics.adoc

Edited chapter %setup

---

community/index.adoc
rhel/master.adoc
source/why-package-rpm.adoc

Pmkovar's text has been used as a source: https://www.softwarecollections.org/en/docs/guide/#sect-Why_to_Package_Software_with_RPM

Added chapter Why Package Software with RPM?

---

source/preparing-software.adoc

Signed-off-by: Matěj Vopálka <matej.vopalka@gmail.com>

Repaired mistake in code block.

---

source/advanced-topics.adoc

Solving bz: https://bugzilla.redhat.com/show_bug.cgi?id=1564079

Added chapter Signing Packages 

---

source/advanced-topics.adoc

Solving BZ bug: https://bugzilla.redhat.com/show_bug.cgi?id=1003962

Added scriptlet -p option use description

---

source/references.adoc

Sorting of references

---

community/index.adoc
rhel/docinfo.xml

name_of_corporate_author_added

---

source/packaging-software.adoc

Edited according to closed merge request #52

Editing a typo 

---

community/index.adoc
rhel/docinfo.xml

Reverts redhat-developer/rpm-packaging-guide#53

Revert "name_of_corporate_author_added"

---

source/hello-world.adoc

Corrected minor grammatical typo.

Str8edgedave

---

source/advanced-topics.adoc
source/packaging-software.adoc

PR fixes tables for humans readable

Tables for humans

---

source/acknowledgements.adoc
source/advanced-topics.adoc
source/features-rhel7.adoc
source/hello-world.adoc
source/introduction.adoc
source/packaging-software.adoc
source/preparing-software.adoc
source/references.adoc
source/why-package-rpm.adoc

This PR fixes #76 
Rewarps the most of paragraphs to 80cols

Rewarps source files

---

source/advanced-topics.adoc
source/packaging-software.adoc

Fixes a few minor grammar and formatting nitpicks.
* Incorrect use of "it's"
* Redundant words
* Oddly placed commas
* Misnumbering

Fix grammar and formatting

---

source/advanced-topics.adoc
source/packaging-software.adoc

Change https://fedorahosted.org/koji to https://pagure.io/koji and http://rpm.org/user_doc/macros.html to https://rpm-software-management.github.io/rpm/manual/macros.html.

Update some URLs
